# Copyright 2020 Hewlett Packard Enterprise Development LP

FROM cray/hms-hmi-service-build-base

# Run unit tests...
RUN set -ex \
    && go test -v -o scsd stash.us.cray.com/HMS/hms-hmi-service/cmd/hmi-service
