#THIS environment sets up all of FAS
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (red fish sims) are all setup and active.
#  The FAS binary is active
#  NO poscsd are exposed to the local system.
#  This will be used for ct testing
networks:
  hbtd:

services:
  ct-tests-functional-wait-for-smd:
    build:
      context: test/ct/
      dockerfile: Dockerfile.wait-for-smd.Dockerfile
    depends_on:
      - cray-hbtd
      - cray-smd
    networks:
      - hbtd
  ct-tests-functional:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/src/libs
    depends_on:
      - cray-hbtd
      - cray-smd
    entrypoint: entrypoint.sh functional -c /src/app/tavern_global_config_ct_test.yaml -p /src/app
    #entrypoint: tail -f /dev/null
    networks:
      - hbtd
  ct-tests-smoke:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    depends_on:
      - cray-hbtd
    entrypoint: entrypoint.sh smoke -f smoke.json -u http://cray-hbtd:28500
    networks:
      - hbtd
  vault:
    hostname: vault
    image: artifactory.algol60.net/docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    networks:
      - hbtd
  vault-kv-enabler:
    image: artifactory.algol60.net/csm-docker/stable/vault-kv-enabler:1.13.4
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds
    depends_on:
      - vault
    networks:
      - hbtd
  redis:
    image: artifactory.algol60.net/docker.io/library/redis:5.0-alpine3.12
    hostname: hms-redfish-redis
    networks:
      - hbtd
  etcd:
    image: artifactory.algol60.net/quay.io/coreos/etcd:v3.4.7
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - hbtd
  cray-hbtd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SM_URL=http://cray-smd:27779/hsm/v2
      - USE_TELEMETRY=1
      - TELEMETRY_HOST=kafka:9092:cray-hmsheartbeat-notifications
      - KV_URL=http://etcd:2379
    networks:
      - hbtd
    ports:
      - "28500:28500"
    depends_on:
      - etcd
      - cray-smd
      - cray-hms-hmcollector
      - redfish-simulator
      - vault-kv-enabler
  hmsds-postgres:
    hostname: hmsds-postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    networks:
      - hbtd
  cray-smd-init:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:2.29.0
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    networks:
      - hbtd
    command: /entrypoint.sh smd-init
  cray-smd:
    image: artifactory.algol60.net/csm-docker/stable/cray-smd:2.29.0
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    networks:
      - hbtd
  zookeeper:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hbtd
  kafka:
    image: artifactory.algol60.net/docker.io/confluentinc/cp-kafka:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - hbtd
  cray-hms-hmcollector:
    image: artifactory.algol60.net/csm-docker/stable/hms-hmcollector:2.33.0
    environment:
      - LOG_LEVEL=TRACE
      - SM_URL=http://cray-smd:27779
      - POLLING_ENABLED=false
      - RF_SUBSCRIBE_ENABLED=false
      - REST_PORT=80
      - VAULT_TOKEN=hms
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./configs/kafka_brokers.json:/configs/kafka_brokers.json
      - ./configs/namespace:/configs/namespace
      - ./configs/token:/configs/token
    networks:
      - hbtd
    depends_on:
      - kafka
  redfish-simulator:
    image: artifactory.algol60.net/csm-docker/stable/hms-redfish-translation-service:1.24.0
    environment:
      - SCHEMA_VERSION=2019.1
      - LOG_LEVEL=TRACE
      - PRIVILEGE_REGISTRY_VERSION=1.0.4
      - SCRIPT_DIR_PREFIX=/tmp/redfish
      - VAULT_TOKEN=hms
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - VAULT_ADDR=http://vault:8200
      - CRAY_VAULT_JWT_FILE=configs/token
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - HTTPS_CERT=configs/rts.crt
      - HTTPS_KEY=configs/rts.key
      - BACKEND_HELPER=RFSimulator
      - PERIODIC_SLEEP=120
      - COLLECTOR_URL=http://cray-hms-hmcollector
      - HSM_URL=http://cray-smd:27779
      - HMS_VAULT_KEYPATH=hms-creds
      - RF_USERNAME=root
      - RF_PASSWORD=testpassword
      - RF_SIMULATOR_XNAMES=x0c0s1b0,x0c0s2b0
    depends_on:
      - redis
      - vault
      - cray-smd
    networks:
      hbtd:
        aliases:
          - x0c0s1b0
          - x0c0s2b0
