# Copyright 2020 Hewlett Packard Enterprise Development LP

FROM cray/hms-hmi-service-build-base

# Run test coverage...
RUN set -ex \
    && go test -cover -v stash.us.cray.com/HMS/hms-hmi-service/cmd/hmi-service
