== Examples
=== Send heartbeat status from a component 
Certain components, commonly nodes, may choose to send periodic heartbeats to the HMS Messaging Service in order to have the HMS Hardware State Manager
track their health.

In HMS Level 2
and Level 3 systems it is ideal to have the HMS Hardware State Manager
track compute nodes' health so that other software agents can be notified
when nodes become operational or when they fail.

Compute node OS images generated by Cray Inc. will have this functionality 
included.  If a custom OS image is to be run whose operational health is 
to be tracked by the HMS Hardware State Manager, this API can be used to
do so.

To send a heartbeat to the Heartbeat Tracking Service, perform a POST 
to the Heartbeat Service URL with a JSON-formatted heartbeat payload.

It is necessary for components to send heartbeats at intervals which
do not exceed the intervals configured by the
Warntime/Errtime operational parameter settings, otherwise the Heartbeat Tracking Service will notify the Hardware State Manager and the component will be flagged. 

Generally this is not done by curl on the command line, but is part of a
heartbeat generator daemon, written in C/C++, Go, Python, etc.  Each of these 
languages has libraries and constructs to do this programatically.  Curl is used in the following examples for ease of demonstration.

[source]
.Heartbeat request payload 

----
       {
           "Component":"component name",
           "Hostname":"componenthost name",
           "NID":"nid number",
           "Status":"component status",
           "Timestamp":"ISO8601 time stamp"
       }


----
[source,bash]
.Use curl to send heartbeat 
----

  curl -k -d '"Component":"x1c0s0b0n0","Hostname":"x1c0s0b0n0","NID":"1234","Status":"OK","Timestamp":"2018-09-04T12:34:56.123456-5Z"}' -X POST https://sms-1/apis/hbtd/hmi/v1/heartbeat

----

=== Get/Set current operational parameters

It is possible to fetch the current state of the heartbeat tracking
operational parameters.  This is done via a ReST 'GET' operation.

[source,bash]
.Get current operational parameters using curl

  curl -k https://sms-1/apis/hbtd/hmi/v1/params | python2 -m json.tool

.Output

  {
    "Debug": "0",
    "Errtime": "20",
    "Interval": "5",
    "Nosm": "0",
    "Port": "28500",
    "Sm_retries": "3",
    "Sm_timeout": "10",
    "Sm_url": "https://api-gateway.default.svc.cluster.local/apis/smd/hsm/v1",
    "Tls_cert": "/etc/cert.pem",
    "Tls_key": "/etc/key.pem",
    "Use_telemetry": "1",
    "Telemetry_host": "kafka:9092:heartbeat_notifications",
    "Warntime": "10"
}

Note that these parameters are also changeable on-the-fly, not requiring
a service restart.  To change a parameter, perform a ReST PATCH operation
with a JSON-formatted payload containing the parameter(s) to be changed
along with their new values.

[source, bash]
.Set Debug Level to 2 in the Heartbeat Tracking Service

  curl -k -d '{"Debug":"2"}' -X PATCH https://sms-1/apis/hbtd/hmi/v1/params | python2 -m json.tool

.Output

  {
    "Debug": "2",
    "Errtime": "20",
    "Interval": "5",
    "Nosm": "0",
    "Port": "28500",
    "Sm_retries": "3",
    "Sm_timeout": "10",
    "Sm_url": "https://api-gateway.default.svc.cluster.local/apis/smd/hsm/v1",
    "Tls_cert": "/etc/cert.pem",
    "Tls_key": "/etc/key.pem",
    "Use_telemetry": "1",
    "Telemetry_host": "kafka:9092:heartbeat_notifications",
    "Warntime": "10"
}

Parameters which are most likely to be modified on the fly are:

  Debug:         Increases the verbosity of the logging

  Warntime:      Change the max time elapsed since last HB received by a
                     component before sending a WARNING to the State Manager

  Errtime:       Change the max time elapsed since last HB received by a
                     component before sending an ALERT to the State Manager

  Sm_retries:    Number of times to retry operations with the State Manager
                     before giving up.

  Sm_timeout:    Max time to wait for a response from the State Manager in
                     any given interaction before giving up.

  Use_telemetry: Turn on or off the ability to dump notifications of 
                     heartbeat state changes to the telemetry bus.

=== Message Bus Telemetry

By default, the Heartbeat Tracking Service dumps heartbeat status
change notifications onto the telemetry bus.  This is essentially the
same information that is told to the State Manager service when 
heartbeat status changes for a component, but in a different format.
These notifications are published to a "topic" on the message bus
called "heartbeat_notifications".

Example of a heartbeat status change notification message:

[source]
.Heartbeat notification telemetry bus payload 

----

    {
        "MessageID": "Heartbeat Change Notification",
        "ID": "x0c1s2b0n3",
        "NewState": "Standby",
        "NewFlag": "Alert",
        "LastHBTimeStamp": "2018-09-04T12:34:56.123456-5Z",
        "Info": "Heartbeat stopped, node is dead."
    }

----

